### ISSUE TITLE
Database upgrade hook not working

### ISSUE THREAD

**Issue by calvinbui** [anchore/anchore-charts#104]
Upgrading from `1.10.0` to `1.11.1`, a DB change is needed from `0.0.13` to `0.0.14`.

All pods are pending, waiting for the DB upgrade with the message:

```
[MainThread] [anchore_manager.cli.service/start()] [WARN] this version of anchore-engine requires the anchore DB version (0.0.14) but we discovered anchore DB version (0.0.13) in the running DB - it is safe to run the upgrade while seeing this message - will retry for 3600 more seconds.
```

The `job` resource upgrading the DB is a post-upgrade hook which will never execute as it is waiting for the pods to be ready (i.e. deployed). But the pods are waiting for the DB to be ready. I ran the job manually (from the manifest in `helm get all <release>`) and the DB upgraded successful and the pods became ready afterwards.

The hook should be either be a `post-install` or `pre-upgrade` instead to avoid this issue.

**Comment by Btodhunter** [comment]
Hey @calvinbui! Sorry to hear that your upgrade job didn't run correctly. Can I get more details about your deployment and the exact errors you ran into? I'm particularly interested in the status/logs of the engine-upgrade job. Our chart has been using a post-upgrade hook ever since the DB upgrade job was introduced in chart version 1.6.0 and this is the first issue with that job hanging. 

The post-upgrade hook does not wait to start the upgrade job until all pods are ready, it waits for all upgraded resources to be scheduled, then blocks until the post-upgrade hook completes. https://helm.sh/docs/topics/charts_hooks/#hooks-and-the-release-lifecycle 

We choose the helm post-upgrade hook with a recreate pod update strategy to force the old pods to terminate before the db upgrade job is started. We made this decision to prevent anchore DB transactions from occurring during the upgrade. The anchore-manager, which is the entrypoint of all anchore containers, will wait until the DB upgrade is finished before starting. During this time you might see some errors in the log about the db version. This also causes the pods to have the 'not ready' status. Once the engine-upgrade job finishes, the other anchore pods should go into the 'ready' status within a few seconds.

**Comment by calvinbui** [comment]
> Can I get more details about your deployment and the exact errors you ran into? I'm particularly interested in the status/logs of the engine-upgrade job. Our chart has been using a post-upgrade hook ever since the DB upgrade job was introduced in chart version 1.6.0 and this is the first issue we've gotten in regards to that job.

This was our first ever upgrade, so we never ran a DB upgrade before. 

The logs were normal for the engine-upgrade job resource that I ran applied manually, without any errors. It's been deleted since.

> The post-upgrade hook does not wait to start the upgrade job until all pods are ready, it waits for all upgraded resources to be scheduled, then blocks until the post-upgrade hook completes. https://helm.sh/docs/topics/charts_hooks/#hooks-and-the-release-lifecycle

The steps only list the `pre-install` and `post-install` hooks however. Reading the table on that page, the `pre-upgrade` description says `Executes on an upgrade request after templates are rendered, but before any resources are updated` closely matches your description. `post-upgrade` says `after all resources have been upgraded` which leads me to believe they have to be in the 'ready' state.

> During this time you might see some errors in the log about the db version. This also causes the pods to have the 'not ready' status. Once the engine-upgrade job finishes, the other anchore pods should go into the 'ready' status within a few seconds.

Yep this is the exact issue. The job never ran and Helm waited until timeout.

---

I can't reproduce this until the next upgrade so I'll close the issue for now until next time.

**Comment by andrejpohlmann** [comment]
Hi, we got the same issue. It occurs when using helm upgrade with --wait. In this case the post-upgrade hook is blocked until the pods are ready, so it deadlocks itself. The problem is discussed in the Github repository of Helm (https://github.com/helm/helm/issues/7740) or on Stack Overflow (https://stackoverflow.com/questions/60262802/how-to-use-wait-with-post-install-hook-in-helm), but currently there seems to be no real solution. We helped us by removing the --wait flag. A workaround could be  using an init container or pre-upgrade instead of post-upgrade, but this needs further changes in the services. What do you think?

**Comment by Btodhunter** [comment]
@andrejpohlmann good observation about `helm upgrage --wait...` that will indeed cause a deadlock with the post-upgrade hook. That is definitely not ideal behavior. 

@calvinbui did you by chance use the --wait option when running the upgrade?

I'm going to re-open this issue until we can figure out a good solution that will allow the --wait option. The pre-upgrade hook isn't ideal because we want all anchore services to shutdown before initiating the db upgrade. An init container might be a better solution, I'll investigate further.

**Comment by rgarcia6520** [comment]
> 
> 
> @andrejpohlmann good observation about helm upgrade --wait - that will indeed cause a deadlock with the post-upgrade hook. That is definitely not ideal behavior.
> 
> @calvinbui did you by chance use the --wait option when running the upgrade?
> 
> I'm going to re-open this issue until we can figure out a good solution that will allow the --wait option. The pre-upgrade hook isn't ideal because we want all anchore services to shutdown before initiating the db upgrade. An init container might be a better solution, I'll investigate further.

Thanks for this info, in our fluxv2 based deployments, we were seeing that deadlock issue with the chart upgrades because fluxv2 helm-controller by default uses an equivalent of that --wait flag, once we disabled it in the flux values for the anchore specific HelmRelease object our chart upgraded successfully from 1.9.X to 1.11.X

**Comment by calvinbui** [comment]
Yep, I used `--wait`

**Comment by bhearn7** [comment]
@Btodhunter +1 for this issue. I'm seeing the same thing when upgrading from 1.11.0 to 1.12.7
