### ISSUE TITLE
Add chart testing process

### ISSUE THREAD

**Issue by Btodhunter** [anchore/anchore-charts#35]
All charts in this repository should go through a unified e2e chart testing process.

There is an example of a chart testing process utilizing GitHub actions for the admission-controller chart. We would like this process initially to be setup in CircleCI so that it utilizes the same system as all other projects. If the CircleCI process is too complex or requires too much custom scripting/setup, we can consider using GitHub Actions instead. 

The initial e2e test setup should use KIND to stand up k8s clusters utilizing multiple versions of k8s and ensure that the chart installs as expected.

**Comment by robertp** [comment]
Reference info:
https://github.com/helm/charts/blob/master/.circleci/config.yml
https://github.com/helm/charts/tree/master/test

**Comment by Btodhunter** [comment]
https://helm.sh/docs/topics/chart_tests/

**Comment by robertp** [comment]
Today I got most of the way through basic linting and helm installing with local CI and CircleCI.

**Comment by robertp** [comment]
Ok, this is working well enough locally, and in CircleCI I can't run it in a large class container so it's timing out on the API coming up.

Shifting gears now to using the helm project ct testing tool on Github Actions.

**Comment by zhill** [comment]
Isn't this basically implemented in the current GHA flow?

**Comment by robertp** [comment]
Hey @zhill, you can see from the first comment that originally when discussing this (Weds) the idea was that having CI in one system would be better than two, so we pointed me in the CircleCI direction initially.  Yesterday I found that using helm's ct tool was a bit involved, so I decided instead in the interest of time to use helm's lint command for linting, and our e2e tests for a smoke test (in CircleCI).

Last night/today, Brady actually just rolled the legacy chart into using the GHA flow and it works well with ct. So given that some work had gone into it already, I buttoned up the CircleCI flow today since it was most of the way there (in my fork).  We should be able to use either or both systems for chart linting and testing now, although it's clear that using the official linting and testing is preferable.

**Comment by robertp** [comment]
As noted this works pretty well and can spread across multiple kubernetes versions using the GHA matrix strategy (https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix).

In a subsequent sprint we will add our own end to end or smoke testing.

**Comment by Btodhunter** [comment]
This has been resolved by updating the GHA workflow.
